import { ExpressionEntry } from "@/lib/types";
import { importedExpressions } from "@/lib/generated-imported-content";

const curatedExpressions: ExpressionEntry[] = [
  {
    id: "en-break-a-leg",
    language: "en",
    expression: "Break a leg",
    meaning: "A friendly way to wish someone good luck before a performance or big moment.",
    usageNote: "Use it before a show, presentation, or audition when you want to sound supportive.",
    exampleSentence: "You are going to do great in the interview. Break a leg!",
    exampleTranslation: "You are going to do great in the interview. Good luck!",
    difficulty: "basic",
    tags: ["encouragement", "work", "performance"]
  },
  {
    id: "en-hit-the-books",
    language: "en",
    expression: "Hit the books",
    meaning: "To study seriously and with focus.",
    usageNote: "Use it when talking about preparing for exams or learning something intensively.",
    exampleSentence: "I have a test tomorrow, so I need to hit the books tonight.",
    exampleTranslation: "I have a test tomorrow, so I need to study seriously tonight.",
    difficulty: "basic",
    tags: ["study", "daily-life"]
  },
  {
    id: "en-under-the-weather",
    language: "en",
    expression: "Under the weather",
    meaning: "Feeling slightly sick or unwell.",
    usageNote: "Use it in casual conversation when you are not feeling your best.",
    exampleSentence: "I am a bit under the weather, so I will stay home today.",
    exampleTranslation: "I feel a little sick, so I will stay home today.",
    difficulty: "basic",
    tags: ["health", "daily-life"]
  },
  {
    id: "en-on-the-same-page",
    language: "en",
    expression: "On the same page",
    meaning: "To understand something in the same way as someone else.",
    usageNote: "Useful in meetings or planning conversations when alignment matters.",
    exampleSentence: "Let us make sure we are on the same page before we start building.",
    exampleTranslation: "Let us make sure we agree before we start building.",
    difficulty: "intermediate",
    tags: ["work", "communication"]
  },
  {
    id: "en-piece-of-cake",
    language: "en",
    expression: "Piece of cake",
    meaning: "Something very easy to do.",
    usageNote: "Use it casually when a task feels easy or simple.",
    exampleSentence: "The setup looks hard, but once you try it, it is a piece of cake.",
    exampleTranslation: "The setup looks hard, but once you try it, it is very easy.",
    difficulty: "basic",
    tags: ["confidence", "daily-life"]
  },
  {
    id: "en-costs-an-arm-and-a-leg",
    language: "en",
    expression: "Costs an arm and a leg",
    meaning: "To be very expensive.",
    usageNote: "Use it when something feels far more expensive than expected.",
    exampleSentence: "That apartment is beautiful, but it costs an arm and a leg.",
    exampleTranslation: "That apartment is beautiful, but it is extremely expensive.",
    difficulty: "intermediate",
    tags: ["money", "daily-life"]
  },
  {
    id: "en-call-it-a-day",
    language: "en",
    expression: "Call it a day",
    meaning: "To stop working on something for now.",
    usageNote: "Use it when you want to end a work session and continue later.",
    exampleSentence: "We have made good progress, so let us call it a day.",
    exampleTranslation: "We have made good progress, so let us stop for today.",
    difficulty: "basic",
    tags: ["work", "time"]
  },
  {
    id: "en-spill-the-beans",
    language: "en",
    expression: "Spill the beans",
    meaning: "To reveal a secret or surprise.",
    usageNote: "Use it when someone shares information earlier than planned.",
    exampleSentence: "I was saving the news for dinner, but my brother spilled the beans.",
    exampleTranslation: "I was saving the news for dinner, but my brother revealed it.",
    difficulty: "intermediate",
    tags: ["communication", "secrets"]
  },
  {
    id: "en-get-the-hang-of-it",
    language: "en",
    expression: "Get the hang of it",
    meaning: "To begin to understand how to do something well.",
    usageNote: "Use it when a new skill starts to feel natural after practice.",
    exampleSentence: "The software felt confusing at first, but I am getting the hang of it now.",
    exampleTranslation: "The software felt confusing at first, but I am starting to understand it now.",
    difficulty: "basic",
    tags: ["learning", "confidence"]
  },
  {
    id: "en-in-hot-water",
    language: "en",
    expression: "In hot water",
    meaning: "In trouble or facing criticism.",
    usageNote: "Use it when someone has caused a problem and now has to deal with the consequences.",
    exampleSentence: "He is in hot water after missing the deadline again.",
    exampleTranslation: "He is in trouble after missing the deadline again.",
    difficulty: "intermediate",
    tags: ["mistakes", "work"]
  },
  {
    id: "en-go-the-extra-mile",
    language: "en",
    expression: "Go the extra mile",
    meaning: "To make a bigger effort than expected.",
    usageNote: "Use it to praise someone for doing more than the minimum.",
    exampleSentence: "She always goes the extra mile for her clients.",
    exampleTranslation: "She always makes an extra effort for her clients.",
    difficulty: "basic",
    tags: ["work", "motivation"]
  },
  {
    id: "en-back-to-square-one",
    language: "en",
    expression: "Back to square one",
    meaning: "Forced to start again from the beginning.",
    usageNote: "Use it when a plan fails and you have to restart.",
    exampleSentence: "The fix did not work, so we are back to square one.",
    exampleTranslation: "The fix did not work, so we have to start again.",
    difficulty: "intermediate",
    tags: ["work", "mistakes"]
  },
  {
    id: "es-pan-comido",
    language: "es",
    expression: "Ser pan comido",
    literalTranslation: "To be eaten bread",
    meaning: "To be very easy.",
    usageNote: "Use it like “piece of cake” when something is simple to do.",
    exampleSentence: "El examen fue pan comido para ella.",
    exampleTranslation: "The exam was a piece of cake for her.",
    difficulty: "basic",
    tags: ["confidence", "study"]
  },
  {
    id: "es-estar-en-las-nubes",
    language: "es",
    expression: "Estar en las nubes",
    literalTranslation: "To be in the clouds",
    meaning: "To be distracted or daydreaming.",
    usageNote: "Use it when someone is mentally somewhere else and not paying attention.",
    exampleSentence: "Perdona, estaba en las nubes y no escuché la pregunta.",
    exampleTranslation: "Sorry, I was daydreaming and did not hear the question.",
    difficulty: "basic",
    tags: ["emotion", "daily-life"]
  },
  {
    id: "es-meter-la-pata",
    language: "es",
    expression: "Meter la pata",
    literalTranslation: "To put in the paw",
    meaning: "To make a mistake or say something awkward.",
    usageNote: "Use it when you want to admit you messed up in a casual way.",
    exampleSentence: "Metí la pata al mencionar su ex pareja.",
    exampleTranslation: "I put my foot in it by mentioning their ex partner.",
    difficulty: "intermediate",
    tags: ["communication", "mistakes"]
  },
  {
    id: "es-tomar-el-pelo",
    language: "es",
    expression: "Tomar el pelo",
    literalTranslation: "To take the hair",
    meaning: "To tease or joke with someone.",
    usageNote: "Use it playfully when someone is not being completely serious.",
    exampleSentence: "No te enfades, solo te estoy tomando el pelo.",
    exampleTranslation: "Do not get upset, I am only teasing you.",
    difficulty: "basic",
    tags: ["humor", "daily-life"]
  },
  {
    id: "es-sin-pelos-en-la-lengua",
    language: "es",
    expression: "Sin pelos en la lengua",
    literalTranslation: "Without hairs on the tongue",
    meaning: "To speak very directly and without hesitation.",
    usageNote: "Use it when someone says exactly what they think without softening it.",
    exampleSentence: "Mi abuela habla sin pelos en la lengua.",
    exampleTranslation: "My grandmother speaks very directly.",
    difficulty: "intermediate",
    tags: ["communication", "personality"]
  },
  {
    id: "es-ponerse-las-pilas",
    language: "es",
    expression: "Ponerse las pilas",
    literalTranslation: "To put in the batteries",
    meaning: "To get moving, focus, and start acting with energy.",
    usageNote: "Use it when someone needs to become more active or serious about something.",
    exampleSentence: "Tenemos poco tiempo, así que hay que ponerse las pilas.",
    exampleTranslation: "We do not have much time, so we need to get moving.",
    difficulty: "basic",
    tags: ["motivation", "work"]
  },
  {
    id: "es-costar-un-rinon",
    language: "es",
    expression: "Costar un riñón",
    literalTranslation: "To cost a kidney",
    meaning: "To be extremely expensive.",
    usageNote: "Use it when something costs far more than it should.",
    exampleSentence: "Ese coche está precioso, pero cuesta un riñón.",
    exampleTranslation: "That car is beautiful, but it costs a fortune.",
    difficulty: "basic",
    tags: ["money", "daily-life"]
  },
  {
    id: "es-estar-hecho-polvo",
    language: "es",
    expression: "Estar hecho polvo",
    literalTranslation: "To be made into dust",
    meaning: "To be exhausted or worn out.",
    usageNote: "Use it after a long day when you have no energy left.",
    exampleSentence: "Después del viaje llegué hecho polvo.",
    exampleTranslation: "After the trip I arrived completely exhausted.",
    difficulty: "basic",
    tags: ["health", "daily-life"]
  },
  {
    id: "es-ir-al-grano",
    language: "es",
    expression: "Ir al grano",
    literalTranslation: "To go to the grain",
    meaning: "To get straight to the point.",
    usageNote: "Use it when you want less small talk and more direct communication.",
    exampleSentence: "Tenemos poco tiempo, así que voy al grano.",
    exampleTranslation: "We have little time, so I will get straight to the point.",
    difficulty: "basic",
    tags: ["communication", "work"]
  },
  {
    id: "es-ser-una-olla-de-grillos",
    language: "es",
    expression: "Ser una olla de grillos",
    literalTranslation: "To be a pot of crickets",
    meaning: "To be noisy, chaotic, or full of confusion.",
    usageNote: "Use it when a place or situation feels messy and hard to control.",
    exampleSentence: "La reunión fue una olla de grillos y nadie escuchaba.",
    exampleTranslation: "The meeting was chaotic and nobody was listening.",
    difficulty: "intermediate",
    tags: ["confusion", "work"]
  },
  {
    id: "es-dar-en-el-clavo",
    language: "es",
    expression: "Dar en el clavo",
    literalTranslation: "To hit the nail",
    meaning: "To be exactly right.",
    usageNote: "Use it when someone explains or guesses something perfectly.",
    exampleSentence: "Con ese comentario diste en el clavo.",
    exampleTranslation: "With that comment, you hit the nail on the head.",
    difficulty: "basic",
    tags: ["communication", "confidence"]
  },
  {
    id: "es-no-tener-pelos-en-la-lengua",
    language: "es",
    expression: "No tener pelos en la lengua",
    literalTranslation: "To not have hairs on the tongue",
    meaning: "To speak very openly and directly.",
    usageNote: "Use it when someone says what they think without softening it.",
    exampleSentence: "Mi tío no tiene pelos en la lengua cuando algo no le gusta.",
    exampleTranslation: "My uncle speaks very directly when he does not like something.",
    difficulty: "intermediate",
    tags: ["communication", "personality"]
  },
  {
    id: "de-ich-verstehe-nur-bahnhof",
    language: "de",
    expression: "Ich verstehe nur Bahnhof",
    literalTranslation: "I only understand train station",
    meaning: "I do not understand anything.",
    usageNote: "Use it humorously when a topic is confusing or full of jargon.",
    exampleSentence: "Bei dem Steuerformular verstehe ich nur Bahnhof.",
    exampleTranslation: "With that tax form, I do not understand anything.",
    difficulty: "intermediate",
    tags: ["confusion", "daily-life"]
  },
  {
    id: "de-die-daumen-druecken",
    language: "de",
    expression: "Die Daumen drücken",
    literalTranslation: "To press the thumbs",
    meaning: "To wish someone luck.",
    usageNote: "Use it before an exam, interview, or important event.",
    exampleSentence: "Ich drücke dir für morgen die Daumen.",
    exampleTranslation: "I am keeping my fingers crossed for you tomorrow.",
    difficulty: "basic",
    tags: ["encouragement", "work"]
  },
  {
    id: "de-ins-kalte-wasser-springen",
    language: "de",
    expression: "Ins kalte Wasser springen",
    literalTranslation: "To jump into cold water",
    meaning: "To do something new without much preparation.",
    usageNote: "Use it when someone has to learn by doing right away.",
    exampleSentence: "Am ersten Arbeitstag musste ich direkt ins kalte Wasser springen.",
    exampleTranslation: "On my first day of work, I had to jump right in.",
    difficulty: "intermediate",
    tags: ["work", "learning"]
  },
  {
    id: "de-zwei-fliegen-mit-einer-klappe-schlagen",
    language: "de",
    expression: "Zwei Fliegen mit einer Klappe schlagen",
    literalTranslation: "To hit two flies with one swat",
    meaning: "To achieve two things with one action.",
    usageNote: "Use it when one plan solves two problems at once.",
    exampleSentence: "Mit dem Spaziergang kaufe ich noch Brot und schlage zwei Fliegen mit einer Klappe.",
    exampleTranslation: "By taking a walk, I can also buy bread and kill two birds with one stone.",
    difficulty: "basic",
    tags: ["efficiency", "daily-life"]
  },
  {
    id: "de-auf-dem-schlauch-stehen",
    language: "de",
    expression: "Auf dem Schlauch stehen",
    literalTranslation: "To stand on the hose",
    meaning: "To be slow to understand something obvious.",
    usageNote: "Use it lightly when you suddenly realize you were missing something simple.",
    exampleSentence: "Jetzt habe ich es verstanden, ich stand total auf dem Schlauch.",
    exampleTranslation: "Now I understand it, I was completely missing the obvious.",
    difficulty: "intermediate",
    tags: ["confusion", "communication"]
  },
  {
    id: "de-das-ist-nicht-mein-bier",
    language: "de",
    expression: "Das ist nicht mein Bier",
    literalTranslation: "That is not my beer",
    meaning: "That is not my problem or responsibility.",
    usageNote: "Use it when you want to distance yourself from an issue.",
    exampleSentence: "Wenn sie später kommen, ist das nicht mein Bier.",
    exampleTranslation: "If they arrive late, that is not my problem.",
    difficulty: "basic",
    tags: ["daily-life", "boundaries"]
  },
  {
    id: "de-tomaten-auf-den-augen-haben",
    language: "de",
    expression: "Tomaten auf den Augen haben",
    literalTranslation: "To have tomatoes on the eyes",
    meaning: "To miss something obvious.",
    usageNote: "Use it playfully when someone overlooks what is right in front of them.",
    exampleSentence: "Der Schlüssel lag auf dem Tisch und ich hatte wohl Tomaten auf den Augen.",
    exampleTranslation: "The key was on the table and I must have missed the obvious.",
    difficulty: "intermediate",
    tags: ["confusion", "daily-life"]
  },
  {
    id: "de-die-katze-im-sack-kaufen",
    language: "de",
    expression: "Die Katze im Sack kaufen",
    literalTranslation: "To buy the cat in the bag",
    meaning: "To buy something without checking it properly first.",
    usageNote: "Use it when warning someone not to agree to something blindly.",
    exampleSentence: "Ohne Demo kaufe ich die Katze nicht im Sack.",
    exampleTranslation: "Without a demo, I will not buy something blindly.",
    difficulty: "intermediate",
    tags: ["money", "decision-making"]
  },
  {
    id: "de-den-roten-faden-verlieren",
    language: "de",
    expression: "Den roten Faden verlieren",
    literalTranslation: "To lose the red thread",
    meaning: "To lose the train of thought.",
    usageNote: "Use it when speaking and suddenly forgetting the main point.",
    exampleSentence: "Warte kurz, ich habe gerade den roten Faden verloren.",
    exampleTranslation: "Wait a second, I just lost my train of thought.",
    difficulty: "basic",
    tags: ["communication", "confusion"]
  },
  {
    id: "de-alles-im-griff-haben",
    language: "de",
    expression: "Alles im Griff haben",
    literalTranslation: "To have everything in the handle",
    meaning: "To have everything under control.",
    usageNote: "Use it when a situation is organized and manageable.",
    exampleSentence: "Keine Sorge, das Team hat alles im Griff.",
    exampleTranslation: "Do not worry, the team has everything under control.",
    difficulty: "basic",
    tags: ["work", "confidence"]
  },
  {
    id: "de-um-den-heissen-brei-reden",
    language: "de",
    expression: "Um den heißen Brei reden",
    literalTranslation: "To talk around the hot porridge",
    meaning: "To avoid saying something directly.",
    usageNote: "Use it when someone keeps circling the point instead of stating it clearly.",
    exampleSentence: "Rede nicht um den heißen Brei und sag es einfach.",
    exampleTranslation: "Do not beat around the bush and just say it.",
    difficulty: "intermediate",
    tags: ["communication", "work"]
  }
];

export const expressions: ExpressionEntry[] = [...curatedExpressions, ...importedExpressions];
